import { db } from '@/db';
import { disputes } from '@/db/schema';
import { randomUUID } from 'crypto';

async function main() {
    const sampleDisputes = [
        {
            taskSubmissionId: 12,
            raisedById: randomUUID(),
            reason: 'Payment not received',
            description: 'I completed the task as specified and it was approved 2 weeks ago, but I have not received payment yet. The task was marked as completed on time and all requirements were met. Please process my payment immediately.',
            status: 'open',
            resolution: null,
            resolvedById: null,
            createdAt: new Date('2024-11-15T10:30:00Z').toISOString(),
            resolvedAt: null,
        },
        {
            taskSubmissionId: 23,
            raisedById: randomUUID(),
            reason: 'Work not as described',
            description: 'The submitted work does not match the task description. The worker provided generic content instead of the custom research requested. Multiple sections are incomplete and do not address the specific requirements outlined in the task.',
            status: 'open',
            resolution: null,
            resolvedById: null,
            createdAt: new Date('2024-11-18T14:20:00Z').toISOString(),
            resolvedAt: null,
        },
        {
            taskSubmissionId: 35,
            raisedById: randomUUID(),
            reason: 'Quality issues',
            description: 'The data entry work contains numerous errors and inconsistencies. Over 30% of entries have formatting issues or incorrect information. This does not meet the quality standards specified in the task requirements.',
            status: 'open',
            resolution: null,
            resolvedById: null,
            createdAt: new Date('2024-11-20T09:15:00Z').toISOString(),
            resolvedAt: null,
        },
        {
            taskSubmissionId: 8,
            raisedById: randomUUID(),
            reason: 'Deadline violation',
            description: 'The task submission was made 3 days after the specified deadline without any prior communication. This caused delays in our project timeline and the work quality appears rushed.',
            status: 'open',
            resolution: null,
            resolvedById: null,
            createdAt: new Date('2024-11-22T16:45:00Z').toISOString(),
            resolvedAt: null,
        },
        {
            taskSubmissionId: 45,
            raisedById: randomUUID(),
            reason: 'Communication problems',
            description: 'The employer has not responded to my clarification requests for over a week. I submitted questions about specific requirements but received no guidance, making it impossible to complete the task properly.',
            status: 'open',
            resolution: null,
            resolvedById: null,
            createdAt: new Date('2024-11-23T11:00:00Z').toISOString(),
            resolvedAt: null,
        },
        {
            taskSubmissionId: 19,
            raisedById: randomUUID(),
            reason: 'Task requirements unclear',
            description: 'The task description lacks critical details about formatting and expected deliverables. I followed best practices but my submission was rejected for not meeting unspecified requirements. The initial brief needs to be more detailed.',
            status: 'under_review',
            resolution: null,
            resolvedById: null,
            createdAt: new Date('2024-11-10T13:30:00Z').toISOString(),
            resolvedAt: null,
        },
        {
            taskSubmissionId: 28,
            raisedById: randomUUID(),
            reason: 'Unfair rejection',
            description: 'My submission was rejected without proper feedback or explanation. I completed all requirements listed in the task description and submitted on time. The rejection appears arbitrary and I request a review of the decision.',
            status: 'under_review',
            resolution: null,
            resolvedById: null,
            createdAt: new Date('2024-11-12T15:20:00Z').toISOString(),
            resolvedAt: null,
        },
        {
            taskSubmissionId: 41,
            raisedById: randomUUID(),
            reason: 'Payment not received',
            description: 'The task was completed and approved 10 days ago but payment is still pending. I have contacted support twice but have not received a response regarding when I will receive my earnings.',
            status: 'under_review',
            resolution: null,
            resolvedById: null,
            createdAt: new Date('2024-11-14T10:00:00Z').toISOString(),
            resolvedAt: null,
        },
        {
            taskSubmissionId: 52,
            raisedById: randomUUID(),
            reason: 'Quality issues',
            description: 'The submitted graphic design work does not match the style guide provided. Colors are incorrect and the layout does not follow the specified dimensions. Multiple revisions are needed to meet the project standards.',
            status: 'under_review',
            resolution: null,
            resolvedById: null,
            createdAt: new Date('2024-11-16T14:30:00Z').toISOString(),
            resolvedAt: null,
        },
        {
            taskSubmissionId: 5,
            raisedById: randomUUID(),
            reason: 'Work not as described',
            description: 'The translation provided is machine-generated rather than professionally translated as specified. The text contains grammatical errors and lacks natural flow that a human translator would provide.',
            status: 'resolved',
            resolution: 'Task reopened for revisions. Worker agreed to provide professional translation within 3 days. Partial payment held until completion.',
            resolvedById: randomUUID(),
            createdAt: new Date('2024-11-05T09:00:00Z').toISOString(),
            resolvedAt: new Date('2024-11-09T16:30:00Z').toISOString(),
        },
        {
            taskSubmissionId: 17,
            raisedById: randomUUID(),
            reason: 'Payment not received',
            description: 'I completed the data analysis task and it was approved, but payment has been stuck in processing for 2 weeks. I need this resolved as soon as possible.',
            status: 'resolved',
            resolution: 'Payment processed successfully. Technical issue with payment gateway caused delay. Full payment released with bonus for inconvenience.',
            resolvedById: randomUUID(),
            createdAt: new Date('2024-11-03T11:15:00Z').toISOString(),
            resolvedAt: new Date('2024-11-08T10:00:00Z').toISOString(),
        },
        {
            taskSubmissionId: 31,
            raisedById: randomUUID(),
            reason: 'Unfair rejection',
            description: 'My logo design was rejected with vague feedback about not meeting expectations. I followed all guidelines and provided multiple variations as requested. This rejection seems unfair without specific improvement suggestions.',
            status: 'resolved',
            resolution: 'Work redone and approved. Employer provided detailed feedback and worker submitted revised designs that met requirements. Full payment processed.',
            resolvedById: randomUUID(),
            createdAt: new Date('2024-11-01T14:00:00Z').toISOString(),
            resolvedAt: new Date('2024-11-06T13:20:00Z').toISOString(),
        },
        {
            taskSubmissionId: 38,
            raisedById: randomUUID(),
            reason: 'Deadline violation',
            description: 'The worker missed the deadline by 5 days without prior communication. The project timeline was negatively impacted and we had to find alternative solutions.',
            status: 'closed',
            resolution: 'Partial refund issued to employer. Worker provided valid reasons for delay (medical emergency) with documentation. Reduced payment processed based on late delivery impact.',
            resolvedById: randomUUID(),
            createdAt: new Date('2024-10-28T10:30:00Z').toISOString(),
            resolvedAt: new Date('2024-11-03T15:45:00Z').toISOString(),
        },
        {
            taskSubmissionId: 44,
            raisedById: randomUUID(),
            reason: 'Communication problems',
            description: 'The worker stopped responding to messages after initial submission. Critical revision requests were ignored for over 10 days, causing project delays.',
            status: 'closed',
            resolution: 'Task cancelled due to lack of communication. Full refund issued to employer. Worker account flagged for review due to unprofessional behavior.',
            resolvedById: randomUUID(),
            createdAt: new Date('2024-10-25T13:00:00Z').toISOString(),
            resolvedAt: new Date('2024-10-31T11:30:00Z').toISOString(),
        },
    ];

    await db.insert(disputes).values(sampleDisputes);
    
    console.log('✅ Disputes seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});