import { db } from '@/db';
import { payments } from '@/db/schema';

async function main() {
    const samplePayments = [
        // EARNINGS (40 records - 50%)
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            taskSubmissionId: 1,
            amount: 25.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #1 completion',
            createdAt: new Date('2024-11-01T10:30:00Z').toISOString(),
            processedAt: new Date('2024-11-01T14:45:00Z').toISOString(),
        },
        {
            userId: 'user_02h5myn3f9a1z4c2o8n7r6x9t5',
            taskSubmissionId: 2,
            amount: 50.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #2 completion',
            createdAt: new Date('2024-11-02T09:15:00Z').toISOString(),
            processedAt: new Date('2024-11-02T18:30:00Z').toISOString(),
        },
        {
            userId: 'user_03h6nzo4g0b2a5d3p9o8s7y0u6',
            taskSubmissionId: 3,
            amount: 15.0,
            currency: 'USDT_TRC20',
            paymentType: 'earning',
            status: 'pending',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #3 completion',
            createdAt: new Date('2024-11-03T11:20:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_04h7oap5h1c3b6e4q0p9t8z1v7',
            taskSubmissionId: 4,
            amount: 75.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #4 completion',
            createdAt: new Date('2024-11-04T08:45:00Z').toISOString(),
            processedAt: new Date('2024-11-05T10:15:00Z').toISOString(),
        },
        {
            userId: 'user_05h8pbq6i2d4c7f5r1q0u9a2w8',
            taskSubmissionId: 5,
            amount: 30.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #5 completion',
            createdAt: new Date('2024-11-05T14:30:00Z').toISOString(),
            processedAt: new Date('2024-11-06T09:20:00Z').toISOString(),
        },
        {
            userId: 'user_06h9qcr7j3e5d8g6s2r1v0b3x9',
            taskSubmissionId: 6,
            amount: 45.0,
            currency: 'USDT_TRC20',
            paymentType: 'earning',
            status: 'pending',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #6 completion',
            createdAt: new Date('2024-11-06T16:00:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_07h0rds8k4f6e9h7t3s2w1c4y0',
            taskSubmissionId: 7,
            amount: 60.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #7 completion',
            createdAt: new Date('2024-11-07T10:15:00Z').toISOString(),
            processedAt: new Date('2024-11-08T12:45:00Z').toISOString(),
        },
        {
            userId: 'user_08h1set9l5g7f0i8u4t3x2d5z1',
            taskSubmissionId: 8,
            amount: 20.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'failed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #8 completion',
            createdAt: new Date('2024-11-08T13:30:00Z').toISOString(),
            processedAt: new Date('2024-11-08T20:15:00Z').toISOString(),
        },
        {
            userId: 'user_09h2tfu0m6h8g1j9v5u4y3e6a2',
            taskSubmissionId: 9,
            amount: 85.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #9 completion',
            createdAt: new Date('2024-11-09T09:00:00Z').toISOString(),
            processedAt: new Date('2024-11-10T15:30:00Z').toISOString(),
        },
        {
            userId: 'user_10h3ugv1n7i9h2k0w6v5z4f7b3',
            taskSubmissionId: 10,
            amount: 40.0,
            currency: 'USDT_TRC20',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #10 completion',
            createdAt: new Date('2024-11-10T11:45:00Z').toISOString(),
            processedAt: new Date('2024-11-11T08:20:00Z').toISOString(),
        },
        {
            userId: 'user_11h4vhw2o8j0i3l1x7w6a5g8c4',
            taskSubmissionId: 11,
            amount: 55.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'pending',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #11 completion',
            createdAt: new Date('2024-11-11T15:20:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_12h5wix3p9k1j4m2y8x7b6h9d5',
            taskSubmissionId: 12,
            amount: 35.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #12 completion',
            createdAt: new Date('2024-11-12T08:30:00Z').toISOString(),
            processedAt: new Date('2024-11-12T22:45:00Z').toISOString(),
        },
        {
            userId: 'user_13h6xjy4q0l2k5n3z9y8c7i0e6',
            taskSubmissionId: 13,
            amount: 70.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #13 completion',
            createdAt: new Date('2024-11-13T12:00:00Z').toISOString(),
            processedAt: new Date('2024-11-14T16:30:00Z').toISOString(),
        },
        {
            userId: 'user_14h7ykz5r1m3l6o4a0z9d8j1f7',
            taskSubmissionId: 14,
            amount: 25.0,
            currency: 'USDT_TRC20',
            paymentType: 'earning',
            status: 'pending',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #14 completion',
            createdAt: new Date('2024-11-14T14:15:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_15h8zla6s2n4m7p5b1a0e9k2g8',
            taskSubmissionId: 15,
            amount: 90.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #15 completion',
            createdAt: new Date('2024-11-15T10:45:00Z').toISOString(),
            processedAt: new Date('2024-11-16T13:20:00Z').toISOString(),
        },
        {
            userId: 'user_16h9amb7t3o5n8q6c2b1f0l3h9',
            taskSubmissionId: 16,
            amount: 50.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #16 completion',
            createdAt: new Date('2024-11-16T09:30:00Z').toISOString(),
            processedAt: new Date('2024-11-17T11:45:00Z').toISOString(),
        },
        {
            userId: 'user_17h0bnc8u4p6o9r7d3c2g1m4i0',
            taskSubmissionId: 17,
            amount: 15.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'failed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #17 completion',
            createdAt: new Date('2024-11-17T13:00:00Z').toISOString(),
            processedAt: new Date('2024-11-17T18:30:00Z').toISOString(),
        },
        {
            userId: 'user_18h1cod9v5q7p0s8e4d3h2n5j1',
            taskSubmissionId: 18,
            amount: 65.0,
            currency: 'USDT_TRC20',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #18 completion',
            createdAt: new Date('2024-11-18T11:15:00Z').toISOString(),
            processedAt: new Date('2024-11-19T14:00:00Z').toISOString(),
        },
        {
            userId: 'user_19h2dpe0w6r8q1t9f5e4i3o6k2',
            taskSubmissionId: 19,
            amount: 30.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'pending',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #19 completion',
            createdAt: new Date('2024-11-19T15:30:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_20h3eqf1x7s9r2u0g6f5j4p7l3',
            taskSubmissionId: 20,
            amount: 45.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #20 completion',
            createdAt: new Date('2024-11-20T08:00:00Z').toISOString(),
            processedAt: new Date('2024-11-21T10:15:00Z').toISOString(),
        },
        {
            userId: 'user_21h4frg2y8t0s3v1h7g6k5q8m4',
            taskSubmissionId: 21,
            amount: 80.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #21 completion',
            createdAt: new Date('2024-11-21T12:45:00Z').toISOString(),
            processedAt: new Date('2024-11-22T16:30:00Z').toISOString(),
        },
        {
            userId: 'user_22h5gsh3z9u1t4w2i8h7l6r9n5',
            taskSubmissionId: 22,
            amount: 20.0,
            currency: 'USDT_TRC20',
            paymentType: 'earning',
            status: 'pending',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #22 completion',
            createdAt: new Date('2024-11-22T14:20:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_23h6hti4a0v2u5x3j9i8m7s0o6',
            taskSubmissionId: 23,
            amount: 95.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #23 completion',
            createdAt: new Date('2024-11-23T09:30:00Z').toISOString(),
            processedAt: new Date('2024-11-24T12:00:00Z').toISOString(),
        },
        {
            userId: 'user_24h7iuj5b1w3v6y4k0j9n8t1p7',
            taskSubmissionId: 24,
            amount: 35.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #24 completion',
            createdAt: new Date('2024-11-24T11:00:00Z').toISOString(),
            processedAt: new Date('2024-11-25T14:45:00Z').toISOString(),
        },
        {
            userId: 'user_25h8jvk6c2x4w7z5l1k0o9u2q8',
            taskSubmissionId: 25,
            amount: 55.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'failed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #25 completion',
            createdAt: new Date('2024-11-25T13:15:00Z').toISOString(),
            processedAt: new Date('2024-11-25T22:00:00Z').toISOString(),
        },
        {
            userId: 'user_26h9kwl7d3y5x8a6m2l1p0v3r9',
            taskSubmissionId: 26,
            amount: 70.0,
            currency: 'USDT_TRC20',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #26 completion',
            createdAt: new Date('2024-11-26T10:30:00Z').toISOString(),
            processedAt: new Date('2024-11-27T13:15:00Z').toISOString(),
        },
        {
            userId: 'user_27h0lxm8e4z6y9b7n3m2q1w4s0',
            taskSubmissionId: 27,
            amount: 25.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'pending',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #27 completion',
            createdAt: new Date('2024-11-27T15:45:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_28h1myn9f5a7z0c8o4n3r2x5t1',
            taskSubmissionId: 28,
            amount: 100.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #28 completion',
            createdAt: new Date('2024-11-28T08:20:00Z').toISOString(),
            processedAt: new Date('2024-11-29T11:00:00Z').toISOString(),
        },
        {
            userId: 'user_29h2nzo0g6b8a1d9p5o4s3y6u2',
            taskSubmissionId: 29,
            amount: 40.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #29 completion',
            createdAt: new Date('2024-11-29T12:30:00Z').toISOString(),
            processedAt: new Date('2024-11-30T15:45:00Z').toISOString(),
        },
        {
            userId: 'user_30h3oap1h7c9b2e0q6p5t4z7v3',
            taskSubmissionId: 30,
            amount: 60.0,
            currency: 'USDT_TRC20',
            paymentType: 'earning',
            status: 'pending',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #30 completion',
            createdAt: new Date('2024-11-30T14:00:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_31h4pbq2i8d0c3f1r7q6u5a8w4',
            taskSubmissionId: 31,
            amount: 75.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #31 completion',
            createdAt: new Date('2024-12-01T09:15:00Z').toISOString(),
            processedAt: new Date('2024-12-02T12:30:00Z').toISOString(),
        },
        {
            userId: 'user_32h5qcr3j9e1d4g2s8r7v6b9x5',
            taskSubmissionId: 32,
            amount: 30.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #32 completion',
            createdAt: new Date('2024-12-02T11:45:00Z').toISOString(),
            processedAt: new Date('2024-12-03T14:20:00Z').toISOString(),
        },
        {
            userId: 'user_33h6rds4k0f2e5h3t9s8w7c0y6',
            taskSubmissionId: 33,
            amount: 85.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'failed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #33 completion',
            createdAt: new Date('2024-12-03T13:30:00Z').toISOString(),
            processedAt: new Date('2024-12-03T19:15:00Z').toISOString(),
        },
        {
            userId: 'user_34h7set5l1g3f6i4u0t9x8d1z7',
            taskSubmissionId: 34,
            amount: 20.0,
            currency: 'USDT_TRC20',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #34 completion',
            createdAt: new Date('2024-12-04T10:00:00Z').toISOString(),
            processedAt: new Date('2024-12-05T13:45:00Z').toISOString(),
        },
        {
            userId: 'user_35h8tfu6m2h4g7j5v1u0y9e2a8',
            taskSubmissionId: 35,
            amount: 50.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'pending',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #35 completion',
            createdAt: new Date('2024-12-05T15:20:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_36h9ugv7n3i5h8k6w2v1z0f3b9',
            taskSubmissionId: 36,
            amount: 65.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #36 completion',
            createdAt: new Date('2024-12-06T08:45:00Z').toISOString(),
            processedAt: new Date('2024-12-07T11:30:00Z').toISOString(),
        },
        {
            userId: 'user_37h0vhw8o4j6i9l7x3w2a1g4c0',
            taskSubmissionId: 37,
            amount: 35.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #37 completion',
            createdAt: new Date('2024-12-07T12:15:00Z').toISOString(),
            processedAt: new Date('2024-12-08T16:00:00Z').toISOString(),
        },
        {
            userId: 'user_38h1wix9p5k7j0m8y4x3b2h5d1',
            taskSubmissionId: 38,
            amount: 90.0,
            currency: 'USDT_TRC20',
            paymentType: 'earning',
            status: 'pending',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #38 completion',
            createdAt: new Date('2024-12-08T14:30:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_39h2xjy0q6l8k1n9z5y4c3i6e2',
            taskSubmissionId: 39,
            amount: 45.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #39 completion',
            createdAt: new Date('2024-12-09T09:00:00Z').toISOString(),
            processedAt: new Date('2024-12-10T12:45:00Z').toISOString(),
        },
        {
            userId: 'user_40h3ykz1r7m9l2o0a6z5d4j7f3',
            taskSubmissionId: 40,
            amount: 55.0,
            currency: 'USD',
            paymentType: 'earning',
            status: 'completed',
            paymentMethod: 'platform_credit',
            paymentAddress: null,
            transactionHash: null,
            notes: 'Payment for task #40 completion',
            createdAt: new Date('2024-12-10T11:30:00Z').toISOString(),
            processedAt: new Date('2024-12-11T15:15:00Z').toISOString(),
        },

        // WITHDRAWALS (24 records - 30%)
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            taskSubmissionId: null,
            amount: 250.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'completed',
            paymentMethod: 'bank',
            paymentAddress: 'Bank Account ****1234',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-11-05T10:00:00Z').toISOString(),
            processedAt: new Date('2024-11-06T14:30:00Z').toISOString(),
        },
        {
            userId: 'user_02h5myn3f9a1z4c2o8n7r6x9t5',
            taskSubmissionId: null,
            amount: 150.0,
            currency: 'USDT_TRC20',
            paymentType: 'withdrawal',
            status: 'completed',
            paymentMethod: 'crypto_wallet',
            paymentAddress: 'TXwdRxK8h9mN3pQ7sT2vU5wZ8aB1cD4eF6',
            transactionHash: '0xf8a3b2c1d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1',
            notes: 'Withdrawal request',
            createdAt: new Date('2024-11-08T11:30:00Z').toISOString(),
            processedAt: new Date('2024-11-09T16:45:00Z').toISOString(),
        },
        {
            userId: 'user_03h6nzo4g0b2a5d3p9o8s7y0u6',
            taskSubmissionId: null,
            amount: 300.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'pending',
            paymentMethod: 'paypal',
            paymentAddress: 'user03@paypal.com',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-11-12T09:15:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_04h7oap5h1c3b6e4q0p9t8z1v7',
            taskSubmissionId: null,
            amount: 175.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'completed',
            paymentMethod: 'bank',
            paymentAddress: 'Bank Account ****5678',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-11-15T13:00:00Z').toISOString(),
            processedAt: new Date('2024-11-16T18:20:00Z').toISOString(),
        },
        {
            userId: 'user_05h8pbq6i2d4c7f5r1q0u9a2w8',
            taskSubmissionId: null,
            amount: 400.0,
            currency: 'USDT_TRC20',
            paymentType: 'withdrawal',
            status: 'completed',
            paymentMethod: 'crypto_wallet',
            paymentAddress: 'TYz9K8h7mL6nO5pQ4rS3tU2vW1xY0zA1B2',
            transactionHash: '0x1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2',
            notes: 'Withdrawal request',
            createdAt: new Date('2024-11-18T14:45:00Z').toISOString(),
            processedAt: new Date('2024-11-19T20:15:00Z').toISOString(),
        },
        {
            userId: 'user_06h9qcr7j3e5d8g6s2r1v0b3x9',
            taskSubmissionId: null,
            amount: 225.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'pending',
            paymentMethod: 'bank',
            paymentAddress: 'Bank Account ****9012',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-11-21T10:30:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_07h0rds8k4f6e9h7t3s2w1c4y0',
            taskSubmissionId: null,
            amount: 350.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'completed',
            paymentMethod: 'paypal',
            paymentAddress: 'user07@paypal.com',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-11-24T12:00:00Z').toISOString(),
            processedAt: new Date('2024-11-25T17:30:00Z').toISOString(),
        },
        {
            userId: 'user_08h1set9l5g7f0i8u4t3x2d5z1',
            taskSubmissionId: null,
            amount: 125.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'failed',
            paymentMethod: 'bank',
            paymentAddress: 'Bank Account ****3456',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-11-27T15:15:00Z').toISOString(),
            processedAt: new Date('2024-11-27T22:45:00Z').toISOString(),
        },
        {
            userId: 'user_09h2tfu0m6h8g1j9v5u4y3e6a2',
            taskSubmissionId: null,
            amount: 275.0,
            currency: 'USDT_TRC20',
            paymentType: 'withdrawal',
            status: 'completed',
            paymentMethod: 'crypto_wallet',
            paymentAddress: 'TC3dE4fG5hI6jK7lM8nO9pQ0rS1tU2vW3x',
            transactionHash: '0x2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3',
            notes: 'Withdrawal request',
            createdAt: new Date('2024-11-30T08:45:00Z').toISOString(),
            processedAt: new Date('2024-12-01T13:20:00Z').toISOString(),
        },
        {
            userId: 'user_10h3ugv1n7i9h2k0w6v5z4f7b3',
            taskSubmissionId: null,
            amount: 500.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'pending',
            paymentMethod: 'paypal',
            paymentAddress: 'user10@paypal.com',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-12-03T11:00:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_11h4vhw2o8j0i3l1x7w6a5g8c4',
            taskSubmissionId: null,
            amount: 200.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'completed',
            paymentMethod: 'bank',
            paymentAddress: 'Bank Account ****7890',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-12-05T13:30:00Z').toISOString(),
            processedAt: new Date('2024-12-06T19:00:00Z').toISOString(),
        },
        {
            userId: 'user_12h5wix3p9k1j4m2y8x7b6h9d5',
            taskSubmissionId: null,
            amount: 325.0,
            currency: 'USDT_TRC20',
            paymentType: 'withdrawal',
            status: 'completed',
            paymentMethod: 'crypto_wallet',
            paymentAddress: 'TD4eF5gH6iJ7kL8mN9oP0qR1sT2uV3wX4y',
            transactionHash: '0x3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4',
            notes: 'Withdrawal request',
            createdAt: new Date('2024-12-07T09:45:00Z').toISOString(),
            processedAt: new Date('2024-12-08T15:30:00Z').toISOString(),
        },
        {
            userId: 'user_13h6xjy4q0l2k5n3z9y8c7i0e6',
            taskSubmissionId: null,
            amount: 150.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'failed',
            paymentMethod: 'bank',
            paymentAddress: 'Bank Account ****2468',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-12-09T12:15:00Z').toISOString(),
            processedAt: new Date('2024-12-09T20:45:00Z').toISOString(),
        },
        {
            userId: 'user_14h7ykz5r1m3l6o4a0z9d8j1f7',
            taskSubmissionId: null,
            amount: 450.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'completed',
            paymentMethod: 'paypal',
            paymentAddress: 'user14@paypal.com',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-12-11T10:00:00Z').toISOString(),
            processedAt: new Date('2024-12-12T16:30:00Z').toISOString(),
        },
        {
            userId: 'user_15h8zla6s2n4m7p5b1a0e9k2g8',
            taskSubmissionId: null,
            amount: 175.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'pending',
            paymentMethod: 'bank',
            paymentAddress: 'Bank Account ****1357',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-12-13T14:20:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_16h9amb7t3o5n8q6c2b1f0l3h9',
            taskSubmissionId: null,
            amount: 300.0,
            currency: 'USDT_TRC20',
            paymentType: 'withdrawal',
            status: 'completed',
            paymentMethod: 'crypto_wallet',
            paymentAddress: 'TE5fG6hI7jK8lM9nO0pQ1rS2tU3vW4xY5z',
            transactionHash: '0x4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5',
            notes: 'Withdrawal request',
            createdAt: new Date('2024-12-15T08:30:00Z').toISOString(),
            processedAt: new Date('2024-12-16T13:00:00Z').toISOString(),
        },
        {
            userId: 'user_17h0bnc8u4p6o9r7d3c2g1m4i0',
            taskSubmissionId: null,
            amount: 225.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'completed',
            paymentMethod: 'bank',
            paymentAddress: 'Bank Account ****9753',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-12-17T11:45:00Z').toISOString(),
            processedAt: new Date('2024-12-18T17:15:00Z').toISOString(),
        },
        {
            userId: 'user_18h1cod9v5q7p0s8e4d3h2n5j1',
            taskSubmissionId: null,
            amount: 375.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'pending',
            paymentMethod: 'paypal',
            paymentAddress: 'user18@paypal.com',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-12-19T13:00:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_19h2dpe0w6r8q1t9f5e4i3o6k2',
            taskSubmissionId: null,
            amount: 100.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'failed',
            paymentMethod: 'bank',
            paymentAddress: 'Bank Account ****8642',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-12-21T15:30:00Z').toISOString(),
            processedAt: new Date('2024-12-21T23:00:00Z').toISOString(),
        },
        {
            userId: 'user_20h3eqf1x7s9r2u0g6f5j4p7l3',
            taskSubmissionId: null,
            amount: 425.0,
            currency: 'USDT_TRC20',
            paymentType: 'withdrawal',
            status: 'completed',
            paymentMethod: 'crypto_wallet',
            paymentAddress: 'TF6gH7iJ8kL9mN0oP1qR2sT3uV4wX5yZ6a',
            transactionHash: '0x5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6',
            notes: 'Withdrawal request',
            createdAt: new Date('2024-12-23T09:00:00Z').toISOString(),
            processedAt: new Date('2024-12-24T14:45:00Z').toISOString(),
        },
        {
            userId: 'user_21h4frg2y8t0s3v1h7g6k5q8m4',
            taskSubmissionId: null,
            amount: 250.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'completed',
            paymentMethod: 'bank',
            paymentAddress: 'Bank Account ****7531',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-12-25T10:30:00Z').toISOString(),
            processedAt: new Date('2024-12-26T16:00:00Z').toISOString(),
        },
        {
            userId: 'user_22h5gsh3z9u1t4w2i8h7l6r9n5',
            taskSubmissionId: null,
            amount: 350.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'pending',
            paymentMethod: 'paypal',
            paymentAddress: 'user22@paypal.com',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-12-27T12:45:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_23h6hti4a0v2u5x3j9i8m7s0o6',
            taskSubmissionId: null,
            amount: 275.0,
            currency: 'USD',
            paymentType: 'withdrawal',
            status: 'completed',
            paymentMethod: 'bank',
            paymentAddress: 'Bank Account ****4826',
            transactionHash: null,
            notes: 'Withdrawal request',
            createdAt: new Date('2024-12-29T14:15:00Z').toISOString(),
            processedAt: new Date('2024-12-30T19:30:00Z').toISOString(),
        },

        // BONUSES (12 records - 15%)
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            taskSubmissionId: null,
            amount: 10.0,
            currency: 'USD',
            paymentType: 'bonus',
            status: 'completed',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Welcome bonus',
            createdAt: new Date('2024-11-01T08:00:00Z').toISOString(),
            processedAt: new Date('2024-11-01T08:05:00Z').toISOString(),
        },
        {
            userId: 'user_05h8pbq6i2d4c7f5r1q0u9a2w8',
            taskSubmissionId: null,
            amount: 25.0,
            currency: 'USD',
            paymentType: 'bonus',
            status: 'completed',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Performance bonus',
            createdAt: new Date('2024-11-10T12:00:00Z').toISOString(),
            processedAt: new Date('2024-11-10T12:30:00Z').toISOString(),
        },
        {
            userId: 'user_10h3ugv1n7i9h2k0w6v5z4f7b3',
            taskSubmissionId: null,
            amount: 15.0,
            currency: 'USDT_TRC20',
            paymentType: 'bonus',
            status: 'pending',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Welcome bonus',
            createdAt: new Date('2024-11-15T09:30:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_15h8zla6s2n4m7p5b1a0e9k2g8',
            taskSubmissionId: null,
            amount: 20.0,
            currency: 'USD',
            paymentType: 'bonus',
            status: 'completed',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Performance bonus',
            createdAt: new Date('2024-11-20T14:00:00Z').toISOString(),
            processedAt: new Date('2024-11-20T15:00:00Z').toISOString(),
        },
        {
            userId: 'user_20h3eqf1x7s9r2u0g6f5j4p7l3',
            taskSubmissionId: null,
            amount: 5.0,
            currency: 'USD',
            paymentType: 'bonus',
            status: 'completed',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Welcome bonus',
            createdAt: new Date('2024-11-25T10:15:00Z').toISOString(),
            processedAt: new Date('2024-11-25T10:20:00Z').toISOString(),
        },
        {
            userId: 'user_25h8jvk6c2x4w7z5l1k0o9u2q8',
            taskSubmissionId: null,
            amount: 25.0,
            currency: 'USD',
            paymentType: 'bonus',
            status: 'failed',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Performance bonus',
            createdAt: new Date('2024-11-30T11:45:00Z').toISOString(),
            processedAt: new Date('2024-11-30T18:30:00Z').toISOString(),
        },
        {
            userId: 'user_30h3oap1h7c9b2e0q6p5t4z7v3',
            taskSubmissionId: null,
            amount: 10.0,
            currency: 'USDT_TRC20',
            paymentType: 'bonus',
            status: 'completed',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Welcome bonus',
            createdAt: new Date('2024-12-02T08:30:00Z').toISOString(),
            processedAt: new Date('2024-12-02T08:35:00Z').toISOString(),
        },
        {
            userId: 'user_35h8tfu6m2h4g7j5v1u0y9e2a8',
            taskSubmissionId: null,
            amount: 15.0,
            currency: 'USD',
            paymentType: 'bonus',
            status: 'pending',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Performance bonus',
            createdAt: new Date('2024-12-05T13:00:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_40h3ykz1r7m9l2o0a6z5d4j7f3',
            taskSubmissionId: null,
            amount: 20.0,
            currency: 'USD',
            paymentType: 'bonus',
            status: 'completed',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Welcome bonus',
            createdAt: new Date('2024-12-08T09:45:00Z').toISOString(),
            processedAt: new Date('2024-12-08T09:50:00Z').toISOString(),
        },
        {
            userId: 'user_32h5qcr3j9e1d4g2s8r7v6b9x5',
            taskSubmissionId: null,
            amount: 25.0,
            currency: 'USD',
            paymentType: 'bonus',
            status: 'completed',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Performance bonus',
            createdAt: new Date('2024-12-12T11:30:00Z').toISOString(),
            processedAt: new Date('2024-12-12T12:00:00Z').toISOString(),
        },
        {
            userId: 'user_28h1myn9f5a7z0c8o4n3r2x5t1',
            taskSubmissionId: null,
            amount: 10.0,
            currency: 'USDT_TRC20',
            paymentType: 'bonus',
            status: 'pending',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Welcome bonus',
            createdAt: new Date('2024-12-15T14:20:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_24h7iuj5b1w3v6y4k0j9n8t1p7',
            taskSubmissionId: null,
            amount: 15.0,
            currency: 'USD',
            paymentType: 'bonus',
            status: 'completed',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Performance bonus',
            createdAt: new Date('2024-12-18T10:00:00Z').toISOString(),
            processedAt: new Date('2024-12-18T10:30:00Z').toISOString(),
        },

        // REFERRALS (4 records - 5%)
        {
            userId: 'user_03h6nzo4g0b2a5d3p9o8s7y0u6',
            taskSubmissionId: null,
            amount: 15.0,
            currency: 'USD',
            paymentType: 'referral',
            status: 'completed',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Referral reward for inviting user',
            createdAt: new Date('2024-11-10T11:00:00Z').toISOString(),
            processedAt: new Date('2024-11-10T11:30:00Z').toISOString(),
        },
        {
            userId: 'user_12h5wix3p9k1j4m2y8x7b6h9d5',
            taskSubmissionId: null,
            amount: 20.0,
            currency: 'USDT_TRC20',
            paymentType: 'referral',
            status: 'completed',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Referral reward for inviting user',
            createdAt: new Date('2024-11-22T13:30:00Z').toISOString(),
            processedAt: new Date('2024-11-22T14:00:00Z').toISOString(),
        },
        {
            userId: 'user_18h1cod9v5q7p0s8e4d3h2n5j1',
            taskSubmissionId: null,
            amount: 10.0,
            currency: 'USD',
            paymentType: 'referral',
            status: 'pending',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Referral reward for inviting user',
            createdAt: new Date('2024-12-01T10:45:00Z').toISOString(),
            processedAt: null,
        },
        {
            userId: 'user_27h0lxm8e4z6y9b7n3m2q1w4s0',
            taskSubmissionId: null,
            amount: 15.0,
            currency: 'USD',
            paymentType: 'referral',
            status: 'completed',
            paymentMethod: null,
            paymentAddress: null,
            transactionHash: null,
            notes: 'Referral reward for inviting user',
            createdAt: new Date('2024-12-10T12:15:00Z').toISOString(),
            processedAt: new Date('2024-12-10T13:00:00Z').toISOString(),
        },
    ];

    await db.insert(payments).values(samplePayments);
    
    console.log('✅ Payments seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});