import { db } from '@/db';
import { tasks, user } from '@/db/schema';
import { eq } from 'drizzle-orm';

async function main() {
    // First, query actual employer IDs from the database
    const employers = await db
        .select({ id: user.id })
        .from(user)
        .where(eq(user.role, 'employer'))
        .limit(7);

    if (employers.length === 0) {
        throw new Error('No employers found in database. Please seed users first.');
    }

    const employerIds = employers.map(e => e.id);
    console.log(`Found ${employerIds.length} employers in database`);

    const baseDate = new Date('2024-01-01');
    
    const sampleTasks = [
        // Open tasks (24 tasks - 60%)
        {
            title: 'Enter 500 product details into Excel spreadsheet',
            description: 'Need someone to input product names, prices, and descriptions from PDF catalog into Excel. Must maintain consistent formatting and check for accuracy.',
            categoryId: 1,
            employerId: employerIds[0],
            status: 'open',
            price: 25.0,
            timeEstimate: 120,
            slots: 1,
            slotsFilled: 0,
            requirements: '["Proficient in Excel", "Attention to detail", "Data entry experience"]',
            createdAt: new Date(baseDate.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 16 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Transcribe 30-minute podcast episode',
            description: 'Accurate transcription needed for business podcast. Include timestamps every 5 minutes and speaker labels.',
            categoryId: 2,
            employerId: employerIds[1],
            status: 'open',
            price: 30.0,
            timeEstimate: 180,
            slots: 1,
            slotsFilled: 0,
            requirements: '["Fast typing speed", "Good listening skills", "Native English speaker"]',
            createdAt: new Date(baseDate.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 19 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Tag and categorize 200 product images',
            description: 'Need help organizing product photos by category and adding descriptive tags. Includes clothing, accessories, and home goods.',
            categoryId: 3,
            employerId: employerIds[2],
            status: 'open',
            price: 20.0,
            timeEstimate: 90,
            slots: 2,
            slotsFilled: 0,
            requirements: '["Basic image editing knowledge", "Organizational skills"]',
            createdAt: new Date(baseDate.getTime() + 8 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 22 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Survey 100 people about coffee preferences',
            description: 'Conduct online surveys asking about favorite coffee types, brewing methods, and purchase frequency. Provide results in spreadsheet format.',
            categoryId: 4,
            employerId: employerIds[3],
            status: 'open',
            price: 45.0,
            timeEstimate: 240,
            slots: 3,
            slotsFilled: 0,
            requirements: '["Good communication skills", "Access to survey tools", "Basic data analysis"]',
            createdAt: new Date(baseDate.getTime() + 10 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 24 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Research 50 competitor pricing strategies',
            description: 'Collect and analyze pricing data from competitor websites. Create comparison chart with price ranges and special offers.',
            categoryId: 5,
            employerId: employerIds[4],
            status: 'open',
            price: 50.0,
            timeEstimate: 180,
            slots: 1,
            slotsFilled: 0,
            requirements: '["Research skills", "Spreadsheet proficiency", "Analytical thinking"]',
            createdAt: new Date(baseDate.getTime() + 12 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: null,
        },
        {
            title: 'Moderate 500 user comments for inappropriate content',
            description: 'Review and flag comments that violate community guidelines. Remove spam and offensive language while maintaining engagement.',
            categoryId: 6,
            employerId: employerIds[5],
            status: 'open',
            price: 35.0,
            timeEstimate: 120,
            slots: 2,
            slotsFilled: 0,
            requirements: '["Good judgment", "Familiarity with content policies", "Fast reader"]',
            createdAt: new Date(baseDate.getTime() + 15 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 22 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Verify 300 business addresses and phone numbers',
            description: 'Cross-check business contact information against online directories. Update incorrect entries and note businesses that have closed.',
            categoryId: 7,
            employerId: employerIds[6],
            status: 'open',
            price: 40.0,
            timeEstimate: 150,
            slots: 1,
            slotsFilled: 0,
            requirements: '["Attention to detail", "Internet research skills", "Reliable internet connection"]',
            createdAt: new Date(baseDate.getTime() + 18 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 32 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Label 1000 images for machine learning dataset',
            description: 'Tag images with accurate labels for training AI model. Categories include animals, vehicles, buildings, and nature scenes.',
            categoryId: 8,
            employerId: employerIds[0],
            status: 'open',
            price: 75.0,
            timeEstimate: 240,
            slots: 5,
            slotsFilled: 0,
            requirements: '["Good visual recognition", "Consistency", "Basic computer skills"]',
            createdAt: new Date(baseDate.getTime() + 20 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Create 20 social media posts from blog content',
            description: 'Transform existing blog articles into engaging social media posts. Include relevant hashtags and optimize for each platform.',
            categoryId: 9,
            employerId: employerIds[1],
            status: 'open',
            price: 30.0,
            timeEstimate: 90,
            slots: 1,
            slotsFilled: 0,
            requirements: '["Social media knowledge", "Creative writing", "Understanding of hashtags"]',
            createdAt: new Date(baseDate.getTime() + 22 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: null,
        },
        {
            title: 'Test website functionality on 10 different devices',
            description: 'Check website responsiveness and functionality across various devices and browsers. Document any bugs or display issues found.',
            categoryId: 10,
            employerId: employerIds[2],
            status: 'open',
            price: 25.0,
            timeEstimate: 120,
            slots: 1,
            slotsFilled: 0,
            requirements: '["Access to multiple devices", "Basic tech knowledge", "Detail-oriented"]',
            createdAt: new Date(baseDate.getTime() + 25 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 35 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Compile list of 100 industry influencers with contact info',
            description: 'Research and create database of key influencers in tech industry. Include social media handles, email addresses, and follower counts.',
            categoryId: 1,
            employerId: employerIds[3],
            status: 'open',
            price: 45.0,
            timeEstimate: 180,
            slots: 1,
            slotsFilled: 0,
            requirements: '["Research skills", "Familiarity with social media", "Data organization"]',
            createdAt: new Date(baseDate.getTime() + 28 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 40 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Proofread and edit 50-page business report',
            description: 'Check for grammar, spelling, and formatting errors. Ensure consistent style and professional tone throughout document.',
            categoryId: 2,
            employerId: employerIds[4],
            status: 'open',
            price: 50.0,
            timeEstimate: 180,
            slots: 1,
            slotsFilled: 0,
            requirements: '["Excellent English grammar", "Proofreading experience", "Attention to detail"]',
            createdAt: new Date(baseDate.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: null,
        },
        {
            title: 'Sort and organize 800 customer feedback responses',
            description: 'Categorize customer feedback into themes like product quality, shipping, customer service. Create summary report with key insights.',
            categoryId: 3,
            employerId: employerIds[5],
            status: 'open',
            price: 40.0,
            timeEstimate: 150,
            slots: 2,
            slotsFilled: 0,
            requirements: '["Analytical skills", "Excel proficiency", "Good communication"]',
            createdAt: new Date(baseDate.getTime() + 32 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 45 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Convert 100 scanned documents to digital text',
            description: 'Use OCR or manual typing to digitize scanned business documents. Maintain original formatting and ensure accuracy.',
            categoryId: 4,
            employerId: employerIds[6],
            status: 'open',
            price: 35.0,
            timeEstimate: 180,
            slots: 1,
            slotsFilled: 0,
            requirements: '["Fast typing", "OCR software experience", "Attention to detail"]',
            createdAt: new Date(baseDate.getTime() + 35 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 48 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Monitor 10 brand mentions across social media for 7 days',
            description: 'Track and report all mentions of company brand on Twitter, Facebook, Instagram. Note sentiment and engagement metrics.',
            categoryId: 5,
            employerId: employerIds[0],
            status: 'open',
            price: 100.0,
            timeEstimate: 240,
            slots: 1,
            slotsFilled: 0,
            requirements: '["Social media expertise", "Analytical skills", "Daily availability"]',
            createdAt: new Date(baseDate.getTime() + 38 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 45 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Validate 500 email addresses for newsletter database',
            description: 'Check email addresses for validity and remove duplicates. Flag suspicious or fake-looking addresses.',
            categoryId: 6,
            employerId: employerIds[1],
            status: 'open',
            price: 20.0,
            timeEstimate: 90,
            slots: 1,
            slotsFilled: 0,
            requirements: '["Basic technical knowledge", "Attention to detail", "Email validation tools"]',
            createdAt: new Date(baseDate.getTime() + 40 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: null,
        },
        {
            title: 'Create summaries for 30 YouTube videos',
            description: 'Watch business-related YouTube videos and create concise 2-3 paragraph summaries. Include key takeaways and timestamps.',
            categoryId: 7,
            employerId: employerIds[2],
            status: 'open',
            price: 45.0,
            timeEstimate: 180,
            slots: 2,
            slotsFilled: 0,
            requirements: '["Good comprehension", "Concise writing", "Video watching capability"]',
            createdAt: new Date(baseDate.getTime() + 42 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 52 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Format 200 product descriptions for e-commerce site',
            description: 'Apply consistent formatting to product descriptions. Add bullet points, bold key features, and optimize for readability.',
            categoryId: 8,
            employerId: employerIds[3],
            status: 'open',
            price: 30.0,
            timeEstimate: 120,
            slots: 1,
            slotsFilled: 0,
            requirements: '["HTML basics", "Attention to formatting", "E-commerce experience"]',
            createdAt: new Date(baseDate.getTime() + 45 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 55 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Collect pricing data from 50 online retailers',
            description: 'Survey online stores for specific product prices. Create spreadsheet comparing prices, shipping costs, and availability.',
            categoryId: 9,
            employerId: employerIds[4],
            status: 'open',
            price: 25.0,
            timeEstimate: 90,
            slots: 1,
            slotsFilled: 0,
            requirements: '["Research skills", "Excel proficiency", "Price comparison experience"]',
            createdAt: new Date(baseDate.getTime() + 48 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: null,
        },
        {
            title: 'Review and rate 100 mobile app user interfaces',
            description: 'Test various mobile apps and rate their user interface design. Provide feedback on usability, aesthetics, and navigation.',
            categoryId: 10,
            employerId: employerIds[5],
            status: 'open',
            price: 50.0,
            timeEstimate: 180,
            slots: 3,
            slotsFilled: 0,
            requirements: '["Mobile device access", "UX knowledge", "Critical thinking"]',
            createdAt: new Date(baseDate.getTime() + 50 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 60 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Verify 150 restaurant menu items against website',
            description: 'Cross-check restaurant menu items, prices, and descriptions against their online presence. Update any discrepancies found.',
            categoryId: 1,
            employerId: employerIds[6],
            status: 'open',
            price: 15.0,
            timeEstimate: 60,
            slots: 1,
            slotsFilled: 0,
            requirements: '["Attention to detail", "Internet access", "Basic research skills"]',
            createdAt: new Date(baseDate.getTime() + 52 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 62 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Clean and standardize 600 contact records',
            description: 'Remove duplicates from contact database and standardize phone number and address formats. Merge similar entries.',
            categoryId: 2,
            employerId: employerIds[0],
            status: 'open',
            price: 40.0,
            timeEstimate: 150,
            slots: 1,
            slotsFilled: 0,
            requirements: '["Data cleaning experience", "Excel skills", "Attention to detail"]',
            createdAt: new Date(baseDate.getTime() + 54 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 65 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Test 25 web forms for functionality and usability',
            description: 'Fill out various web forms and document any errors, validation issues, or confusing elements. Provide improvement suggestions.',
            categoryId: 3,
            employerId: employerIds[1],
            status: 'open',
            price: 20.0,
            timeEstimate: 90,
            slots: 2,
            slotsFilled: 0,
            requirements: '["Web browsing skills", "Attention to detail", "Basic tech knowledge"]',
            createdAt: new Date(baseDate.getTime() + 56 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: null,
        },
        {
            title: 'Classify 400 support tickets by urgency and category',
            description: 'Review customer support tickets and assign priority levels. Categorize by issue type and identify urgent cases.',
            categoryId: 4,
            employerId: employerIds[2],
            status: 'open',
            price: 35.0,
            timeEstimate: 120,
            slots: 1,
            slotsFilled: 0,
            requirements: '["Customer service experience", "Good judgment", "Fast reader"]',
            createdAt: new Date(baseDate.getTime() + 58 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 68 * 24 * 60 * 60 * 1000).toISOString(),
        },

        // In Progress tasks (10 tasks - 25%)
        {
            title: 'Translate 50 product descriptions from English to Spanish',
            description: 'Provide accurate translations of e-commerce product descriptions. Maintain marketing tone and cultural relevance.',
            categoryId: 5,
            employerId: employerIds[3],
            status: 'in_progress',
            price: 50.0,
            timeEstimate: 180,
            slots: 1,
            slotsFilled: 1,
            requirements: '["Fluent in Spanish and English", "Translation experience", "Marketing knowledge"]',
            createdAt: new Date(baseDate.getTime() + 3 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 20 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Identify and remove 300 duplicate entries from database',
            description: 'Find and merge duplicate customer records while preserving important data. Create report of changes made.',
            categoryId: 6,
            employerId: employerIds[4],
            status: 'in_progress',
            price: 30.0,
            timeEstimate: 120,
            slots: 1,
            slotsFilled: 1,
            requirements: '["Database experience", "Attention to detail", "Data management skills"]',
            createdAt: new Date(baseDate.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 25 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Create alt text descriptions for 250 website images',
            description: 'Write descriptive alt text for images to improve accessibility. Keep descriptions concise but informative.',
            categoryId: 7,
            employerId: employerIds[5],
            status: 'in_progress',
            price: 25.0,
            timeEstimate: 90,
            slots: 2,
            slotsFilled: 1,
            requirements: '["Writing skills", "Understanding of accessibility", "Image description experience"]',
            createdAt: new Date(baseDate.getTime() + 11 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: null,
        },
        {
            title: 'Extract data from 80 PDF invoices into spreadsheet',
            description: 'Transfer invoice data including amounts, dates, and vendor information into organized Excel format.',
            categoryId: 8,
            employerId: employerIds[6],
            status: 'in_progress',
            price: 35.0,
            timeEstimate: 150,
            slots: 1,
            slotsFilled: 1,
            requirements: '["Data entry skills", "Excel proficiency", "Accuracy"]',
            createdAt: new Date(baseDate.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 28 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Compare features of 40 competing SaaS products',
            description: 'Research and create comparison matrix of software features, pricing, and user reviews. Highlight strengths and weaknesses.',
            categoryId: 9,
            employerId: employerIds[0],
            status: 'in_progress',
            price: 75.0,
            timeEstimate: 240,
            slots: 1,
            slotsFilled: 1,
            requirements: '["Research skills", "Tech industry knowledge", "Analytical thinking"]',
            createdAt: new Date(baseDate.getTime() + 17 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 35 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Review and approve 200 user-submitted photos',
            description: 'Check uploaded photos for quality and appropriateness. Reject photos that violate guidelines and approve suitable ones.',
            categoryId: 10,
            employerId: employerIds[1],
            status: 'in_progress',
            price: 20.0,
            timeEstimate: 90,
            slots: 3,
            slotsFilled: 2,
            requirements: '["Good judgment", "Fast decision-making", "Understanding of content policies"]',
            createdAt: new Date(baseDate.getTime() + 21 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 32 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Update 150 product specifications with new information',
            description: 'Add recently released specifications to existing product listings. Ensure consistency with brand guidelines.',
            categoryId: 1,
            employerId: employerIds[2],
            status: 'in_progress',
            price: 30.0,
            timeEstimate: 120,
            slots: 1,
            slotsFilled: 1,
            requirements: '["Attention to detail", "Product knowledge", "Data entry skills"]',
            createdAt: new Date(baseDate.getTime() + 26 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: null,
        },
        {
            title: 'Compile weekly social media engagement report',
            description: 'Gather metrics from all social platforms and create summary report. Include likes, shares, comments, and follower growth.',
            categoryId: 2,
            employerId: employerIds[3],
            status: 'in_progress',
            price: 25.0,
            timeEstimate: 90,
            slots: 1,
            slotsFilled: 1,
            requirements: '["Social media knowledge", "Data analysis", "Report writing"]',
            createdAt: new Date(baseDate.getTime() + 29 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 36 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Find and list 75 relevant blog post topics for tech startup',
            description: 'Research trending topics in tech industry and suggest blog post ideas. Include target keywords and audience appeal.',
            categoryId: 3,
            employerId: employerIds[4],
            status: 'in_progress',
            price: 30.0,
            timeEstimate: 120,
            slots: 1,
            slotsFilled: 1,
            requirements: '["Content strategy knowledge", "Tech industry awareness", "SEO basics"]',
            createdAt: new Date(baseDate.getTime() + 33 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 43 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Verify information in 120 business directory listings',
            description: 'Confirm accuracy of business hours, addresses, and contact details. Update outdated information and flag closed businesses.',
            categoryId: 4,
            employerId: employerIds[5],
            status: 'in_progress',
            price: 25.0,
            timeEstimate: 90,
            slots: 2,
            slotsFilled: 1,
            requirements: '["Research skills", "Attention to detail", "Data verification experience"]',
            createdAt: new Date(baseDate.getTime() + 37 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 47 * 24 * 60 * 60 * 1000).toISOString(),
        },

        // Completed tasks (4 tasks - 10%)
        {
            title: 'Organize 400 customer reviews by star rating',
            description: 'Sort customer feedback into categories based on ratings. Highlight common themes in positive and negative reviews.',
            categoryId: 5,
            employerId: employerIds[6],
            status: 'completed',
            price: 30.0,
            timeEstimate: 120,
            slots: 1,
            slotsFilled: 1,
            requirements: '["Organizational skills", "Reading comprehension", "Basic analysis"]',
            createdAt: new Date(baseDate.getTime() + 1 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Convert 60 audio recordings to written format',
            description: 'Transcribe interview recordings with accurate timestamps. Include speaker identification and clarify unclear sections.',
            categoryId: 6,
            employerId: employerIds[0],
            status: 'completed',
            price: 75.0,
            timeEstimate: 240,
            slots: 2,
            slotsFilled: 2,
            requirements: '["Fast typing", "Good listening skills", "Transcription experience"]',
            createdAt: new Date(baseDate.getTime() + 4 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 18 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Check 100 links on website for broken pages',
            description: 'Test all hyperlinks throughout website and document any that return errors. Provide list of working and broken links.',
            categoryId: 7,
            employerId: employerIds[1],
            status: 'completed',
            price: 15.0,
            timeEstimate: 60,
            slots: 1,
            slotsFilled: 1,
            requirements: '["Basic web knowledge", "Attention to detail", "Patience"]',
            createdAt: new Date(baseDate.getTime() + 6 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 20 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Rate quality of 300 product photos',
            description: 'Review product images for lighting, clarity, and composition. Score each photo and suggest which need replacement.',
            categoryId: 8,
            employerId: employerIds[2],
            status: 'completed',
            price: 25.0,
            timeEstimate: 90,
            slots: 3,
            slotsFilled: 3,
            requirements: '["Eye for quality", "Photography knowledge helpful", "Quick decision-making"]',
            createdAt: new Date(baseDate.getTime() + 9 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: null,
        },

        // Cancelled tasks (2 tasks - 5%)
        {
            title: 'Manually input 2000 legacy records into new system',
            description: 'Transfer old customer data from paper records into digital database. Requires careful attention to preserve accuracy.',
            categoryId: 9,
            employerId: employerIds[3],
            status: 'cancelled',
            price: 100.0,
            timeEstimate: 360,
            slots: 1,
            slotsFilled: 0,
            requirements: '["Data entry expertise", "Patience", "High accuracy rate"]',
            createdAt: new Date(baseDate.getTime() + 13 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 27 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Analyze sentiment of 500 customer service call transcripts',
            description: 'Read through call transcripts and categorize customer sentiment as positive, neutral, or negative. Note key concerns.',
            categoryId: 10,
            employerId: employerIds[4],
            status: 'cancelled',
            price: 50.0,
            timeEstimate: 180,
            slots: 2,
            slotsFilled: 0,
            requirements: '["Reading comprehension", "Emotional intelligence", "Analysis skills"]',
            createdAt: new Date(baseDate.getTime() + 16 * 24 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(baseDate.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(tasks).values(sampleTasks);
    
    console.log('✅ Tasks seeder completed successfully with 40 tasks');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});