import { db } from '@/db';
import { userStats } from '@/db/schema';

async function main() {
    const sampleUserStats = [
        // Workers (first 15 users) - varied experience levels
        {
            userId: 'user_worker_01h4kxt2e8z9y3b1',
            tasksCompleted: 45,
            tasksPosted: 0,
            totalEarned: 2250.0,
            totalSpent: 0,
            averageRating: 4.8,
            successRate: 0.95,
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        {
            userId: 'user_worker_02h4kxt2e8z9y3b2',
            tasksCompleted: 32,
            tasksPosted: 0,
            totalEarned: 1600.0,
            totalSpent: 0,
            averageRating: 4.6,
            successRate: 0.88,
            updatedAt: new Date('2024-12-09').toISOString(),
        },
        {
            userId: 'user_worker_03h4kxt2e8z9y3b3',
            tasksCompleted: 28,
            tasksPosted: 0,
            totalEarned: 1400.0,
            totalSpent: 0,
            averageRating: 4.5,
            successRate: 0.92,
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            userId: 'user_worker_04h4kxt2e8z9y3b4',
            tasksCompleted: 50,
            tasksPosted: 0,
            totalEarned: 2500.0,
            totalSpent: 0,
            averageRating: 5.0,
            successRate: 1.0,
            updatedAt: new Date('2024-12-11').toISOString(),
        },
        {
            userId: 'user_worker_05h4kxt2e8z9y3b5',
            tasksCompleted: 18,
            tasksPosted: 0,
            totalEarned: 900.0,
            totalSpent: 0,
            averageRating: 4.2,
            successRate: 0.85,
            updatedAt: new Date('2024-12-12').toISOString(),
        },
        {
            userId: 'user_worker_06h4kxt2e8z9y3b6',
            tasksCompleted: 12,
            tasksPosted: 0,
            totalEarned: 600.0,
            totalSpent: 0,
            averageRating: 4.0,
            successRate: 0.80,
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        {
            userId: 'user_worker_07h4kxt2e8z9y3b7',
            tasksCompleted: 38,
            tasksPosted: 0,
            totalEarned: 1900.0,
            totalSpent: 0,
            averageRating: 4.7,
            successRate: 0.90,
            updatedAt: new Date('2024-12-09').toISOString(),
        },
        {
            userId: 'user_worker_08h4kxt2e8z9y3b8',
            tasksCompleted: 5,
            tasksPosted: 0,
            totalEarned: 250.0,
            totalSpent: 0,
            averageRating: 3.8,
            successRate: 0.75,
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            userId: 'user_worker_09h4kxt2e8z9y3b9',
            tasksCompleted: 42,
            tasksPosted: 0,
            totalEarned: 2100.0,
            totalSpent: 0,
            averageRating: 4.9,
            successRate: 0.97,
            updatedAt: new Date('2024-12-11').toISOString(),
        },
        {
            userId: 'user_worker_10h4kxt2e8z9y3b10',
            tasksCompleted: 25,
            tasksPosted: 0,
            totalEarned: 1250.0,
            totalSpent: 0,
            averageRating: 4.4,
            successRate: 0.87,
            updatedAt: new Date('2024-12-12').toISOString(),
        },
        {
            userId: 'user_worker_11h4kxt2e8z9y3b11',
            tasksCompleted: 15,
            tasksPosted: 0,
            totalEarned: 750.0,
            totalSpent: 0,
            averageRating: 4.1,
            successRate: 0.82,
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        {
            userId: 'user_worker_12h4kxt2e8z9y3b12',
            tasksCompleted: 8,
            tasksPosted: 0,
            totalEarned: 400.0,
            totalSpent: 0,
            averageRating: 3.9,
            successRate: 0.78,
            updatedAt: new Date('2024-12-09').toISOString(),
        },
        {
            userId: 'user_worker_13h4kxt2e8z9y3b13',
            tasksCompleted: 35,
            tasksPosted: 0,
            totalEarned: 1750.0,
            totalSpent: 0,
            averageRating: 4.6,
            successRate: 0.89,
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            userId: 'user_worker_14h4kxt2e8z9y3b14',
            tasksCompleted: 22,
            tasksPosted: 0,
            totalEarned: 1100.0,
            totalSpent: 0,
            averageRating: 4.3,
            successRate: 0.86,
            updatedAt: new Date('2024-12-11').toISOString(),
        },
        {
            userId: 'user_worker_15h4kxt2e8z9y3b15',
            tasksCompleted: 48,
            tasksPosted: 0,
            totalEarned: 2400.0,
            totalSpent: 0,
            averageRating: 4.9,
            successRate: 0.96,
            updatedAt: new Date('2024-12-12').toISOString(),
        },
        // Employers (next 7 users) - varied posting activity
        {
            userId: 'user_employer_01h4kxt2e8z9y3c1',
            tasksCompleted: 0,
            tasksPosted: 25,
            totalEarned: 0,
            totalSpent: 3000.0,
            averageRating: 4.8,
            successRate: 0.96,
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        {
            userId: 'user_employer_02h4kxt2e8z9y3c2',
            tasksCompleted: 0,
            tasksPosted: 15,
            totalEarned: 0,
            totalSpent: 1800.0,
            averageRating: 4.6,
            successRate: 0.90,
            updatedAt: new Date('2024-12-09').toISOString(),
        },
        {
            userId: 'user_employer_03h4kxt2e8z9y3c3',
            tasksCompleted: 0,
            tasksPosted: 8,
            totalEarned: 0,
            totalSpent: 960.0,
            averageRating: 4.4,
            successRate: 0.85,
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            userId: 'user_employer_04h4kxt2e8z9y3c4',
            tasksCompleted: 0,
            tasksPosted: 20,
            totalEarned: 0,
            totalSpent: 2400.0,
            averageRating: 4.9,
            successRate: 0.95,
            updatedAt: new Date('2024-12-11').toISOString(),
        },
        {
            userId: 'user_employer_05h4kxt2e8z9y3c5',
            tasksCompleted: 0,
            tasksPosted: 3,
            totalEarned: 0,
            totalSpent: 360.0,
            averageRating: 3.8,
            successRate: 0.80,
            updatedAt: new Date('2024-12-12').toISOString(),
        },
        {
            userId: 'user_employer_06h4kxt2e8z9y3c6',
            tasksCompleted: 0,
            tasksPosted: 12,
            totalEarned: 0,
            totalSpent: 1440.0,
            averageRating: 4.5,
            successRate: 0.88,
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        {
            userId: 'user_employer_07h4kxt2e8z9y3c7',
            tasksCompleted: 0,
            tasksPosted: 18,
            totalEarned: 0,
            totalSpent: 2160.0,
            averageRating: 4.7,
            successRate: 0.92,
            updatedAt: new Date('2024-12-09').toISOString(),
        },
        // Admins (last 3 users) - testing platform with minimal activity
        {
            userId: 'user_admin_01h4kxt2e8z9y3d1',
            tasksCompleted: 10,
            tasksPosted: 5,
            totalEarned: 500.0,
            totalSpent: 500.0,
            averageRating: 5.0,
            successRate: 1.0,
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            userId: 'user_admin_02h4kxt2e8z9y3d2',
            tasksCompleted: 5,
            tasksPosted: 2,
            totalEarned: 250.0,
            totalSpent: 200.0,
            averageRating: 4.9,
            successRate: 1.0,
            updatedAt: new Date('2024-12-11').toISOString(),
        },
        {
            userId: 'user_admin_03h4kxt2e8z9y3d3',
            tasksCompleted: 0,
            tasksPosted: 0,
            totalEarned: 0,
            totalSpent: 0,
            averageRating: 4.5,
            successRate: 1.0,
            updatedAt: new Date('2024-12-12').toISOString(),
        },
    ];

    await db.insert(userStats).values(sampleUserStats);
    
    console.log('✅ User stats seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});