import { db } from '@/db';
import { user } from '@/db/schema';
import { randomUUID } from 'crypto';

async function main() {
    const now = new Date();
    const sixMonthsAgo = new Date(now.getTime() - 180 * 24 * 60 * 60 * 1000);

    const getRandomDateInRange = (start: Date, end: Date): Date => {
        const startTime = start.getTime();
        const endTime = end.getTime();
        const randomTime = startTime + Math.random() * (endTime - startTime);
        return new Date(randomTime);
    };

    const sampleUsers = [
        // Workers (15)
        {
            id: randomUUID(),
            name: 'John Smith',
            email: 'john.smith@example.com',
            emailVerified: true,
            image: 'https://i.pravatar.cc/150?img=1',
            role: 'worker',
            avatar: 'https://i.pravatar.cc/150?img=1',
            bio: 'Experienced data entry specialist with 5+ years in the field',
            phone: '+1-555-0123',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Sarah Johnson',
            email: 'sarah.j@example.com',
            emailVerified: true,
            image: 'https://i.pravatar.cc/150?img=2',
            role: 'worker',
            avatar: 'https://i.pravatar.cc/150?img=2',
            bio: 'Detail-oriented transcriptionist specializing in legal documents',
            phone: '+1-555-0124',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Michael Chen',
            email: 'michael.chen@example.com',
            emailVerified: true,
            image: null,
            role: 'worker',
            avatar: null,
            bio: 'Fast typist with 5 years experience in content writing',
            phone: null,
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Emma Davis',
            email: 'emma.davis@example.com',
            emailVerified: true,
            image: 'https://i.pravatar.cc/150?img=3',
            role: 'worker',
            avatar: 'https://i.pravatar.cc/150?img=3',
            bio: 'Professional virtual assistant with strong organizational skills',
            phone: '+1-555-0125',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Alex Rodriguez',
            email: 'alex.rodriguez@example.com',
            emailVerified: true,
            image: null,
            role: 'worker',
            avatar: null,
            bio: 'Freelance researcher with expertise in market analysis',
            phone: '+1-555-0126',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Jessica Martinez',
            email: 'jessica.m@example.com',
            emailVerified: true,
            image: 'https://i.pravatar.cc/150?img=4',
            role: 'worker',
            avatar: 'https://i.pravatar.cc/150?img=4',
            bio: 'Experienced in web research and data collection tasks',
            phone: null,
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'David Wilson',
            email: 'david.wilson@example.com',
            emailVerified: true,
            image: null,
            role: 'worker',
            avatar: null,
            bio: 'Skilled in image annotation and content moderation',
            phone: '+1-555-0127',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Maria Garcia',
            email: 'maria.garcia@example.com',
            emailVerified: true,
            image: 'https://i.pravatar.cc/150?img=5',
            role: 'worker',
            avatar: 'https://i.pravatar.cc/150?img=5',
            bio: 'Professional proofreader and editor with attention to detail',
            phone: '+1-555-0128',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'James Taylor',
            email: 'james.taylor@example.com',
            emailVerified: true,
            image: null,
            role: 'worker',
            avatar: null,
            bio: 'Data entry specialist with high accuracy rate',
            phone: null,
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Linda Brown',
            email: 'linda.brown@example.com',
            emailVerified: true,
            image: 'https://i.pravatar.cc/150?img=6',
            role: 'worker',
            avatar: 'https://i.pravatar.cc/150?img=6',
            bio: 'Customer service expert with excellent communication skills',
            phone: '+1-555-0129',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Robert Anderson',
            email: 'robert.anderson@example.com',
            emailVerified: true,
            image: null,
            role: 'worker',
            avatar: null,
            bio: 'Experienced in audio transcription and captioning',
            phone: null,
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Jennifer Lee',
            email: 'jennifer.lee@example.com',
            emailVerified: true,
            image: 'https://i.pravatar.cc/150?img=7',
            role: 'worker',
            avatar: 'https://i.pravatar.cc/150?img=7',
            bio: 'Freelance translator specializing in multiple languages',
            phone: '+1-555-0130',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Kevin White',
            email: 'kevin.white@example.com',
            emailVerified: true,
            image: null,
            role: 'worker',
            avatar: null,
            bio: 'Social media content creator with creative flair',
            phone: '+1-555-0131',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Amanda Thomas',
            email: 'amanda.thomas@example.com',
            emailVerified: true,
            image: 'https://i.pravatar.cc/150?img=8',
            role: 'worker',
            avatar: 'https://i.pravatar.cc/150?img=8',
            bio: 'Online survey specialist with fast completion times',
            phone: null,
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Christopher Moore',
            email: 'chris.moore@example.com',
            emailVerified: true,
            image: null,
            role: 'worker',
            avatar: null,
            bio: 'Quality assurance tester with keen eye for detail',
            phone: '+1-555-0132',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },

        // Employers (7)
        {
            id: randomUUID(),
            name: 'Daniel Park',
            email: 'daniel.park@example.com',
            emailVerified: true,
            image: 'https://i.pravatar.cc/150?img=9',
            role: 'employer',
            avatar: 'https://i.pravatar.cc/150?img=9',
            bio: 'Running a digital marketing agency with 50+ clients',
            phone: '+1-555-0133',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Patricia Clark',
            email: 'patricia.clark@example.com',
            emailVerified: true,
            image: null,
            role: 'employer',
            avatar: null,
            bio: 'E-commerce business owner specializing in handmade crafts',
            phone: '+1-555-0134',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Thomas Wright',
            email: 'thomas.wright@example.com',
            emailVerified: true,
            image: 'https://i.pravatar.cc/150?img=10',
            role: 'employer',
            avatar: 'https://i.pravatar.cc/150?img=10',
            bio: 'Content creator needing help with video editing and research',
            phone: null,
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Sandra Lewis',
            email: 'sandra.lewis@example.com',
            emailVerified: true,
            image: null,
            role: 'employer',
            avatar: null,
            bio: 'Startup founder looking for data collection assistance',
            phone: '+1-555-0135',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Richard Hall',
            email: 'richard.hall@example.com',
            emailVerified: true,
            image: 'https://i.pravatar.cc/150?img=11',
            role: 'employer',
            avatar: 'https://i.pravatar.cc/150?img=11',
            bio: 'Online course creator seeking transcription services',
            phone: '+1-555-0136',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Nancy King',
            email: 'nancy.king@example.com',
            emailVerified: true,
            image: null,
            role: 'employer',
            avatar: null,
            bio: 'Real estate agent requiring administrative support',
            phone: null,
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Mark Turner',
            email: 'mark.turner@example.com',
            emailVerified: true,
            image: 'https://i.pravatar.cc/150?img=12',
            role: 'employer',
            avatar: 'https://i.pravatar.cc/150?img=12',
            bio: 'Software company owner needing beta testers and feedback',
            phone: '+1-555-0137',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },

        // Admins (3)
        {
            id: randomUUID(),
            name: 'Rachel Green',
            email: 'rachel.green@taskinn.com',
            emailVerified: true,
            image: 'https://i.pravatar.cc/150?img=13',
            role: 'admin',
            avatar: 'https://i.pravatar.cc/150?img=13',
            bio: 'Platform administrator overseeing operations',
            phone: '+1-555-0138',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Steven Cooper',
            email: 'steven.cooper@taskinn.com',
            emailVerified: true,
            image: null,
            role: 'admin',
            avatar: null,
            bio: 'Customer support lead managing user queries',
            phone: '+1-555-0139',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
        {
            id: randomUUID(),
            name: 'Karen Bailey',
            email: 'karen.bailey@taskinn.com',
            emailVerified: true,
            image: 'https://i.pravatar.cc/150?img=14',
            role: 'admin',
            avatar: 'https://i.pravatar.cc/150?img=14',
            bio: 'Quality assurance manager ensuring platform integrity',
            phone: '+1-555-0140',
            createdAt: getRandomDateInRange(sixMonthsAgo, now),
            updatedAt: getRandomDateInRange(sixMonthsAgo, now),
        },
    ];

    await db.insert(user).values(sampleUsers);
    
    console.log('✅ Users seeder completed successfully - 25 users created (15 workers, 7 employers, 3 admins)');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});